//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// This file was almost autogenerated by cuetsy.
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import { CanvasFrameOptions, DEFAULT_CANVAS_ELEMENT_CONFIG } from 'app/features/canvas';

export const modelVersion = Object.freeze([1, 0]);

export interface PanelOptions {
  inlineEditing: boolean;
  showAdvancedTypes: boolean;
  root: CanvasFrameOptions;
}

export const defaultPanelOptions: PanelOptions = {
  inlineEditing: true,
  showAdvancedTypes: false,
  root: {
    elements: [
      {
        ...DEFAULT_CANVAS_ELEMENT_CONFIG,
      },
    ],
  } as unknown as CanvasFrameOptions,
};
